혼자 공부하는 머신런닝, 딥러닝.

파이썬 머신러닝 완벽 가이드

데이터 과학을 위한 파이썬 완벽 가이드.

1순위 핸즈온 머신러닝

2순위 머신 러닝 교과서 with 파이썬, 사이킷런, 텐서플로 

3순위 파이썬 라이브러리를 활용한 머신러닝 -> 사이킷 런을 만든 사람이 저자. 

In [1]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
np1 = np.array([1, 4, 5, 8], float)
np1

array([1., 4., 5., 8.])

In [7]:
type(np1)

numpy.ndarray

In [8]:
np1[1]

4.0

In [9]:
np1[0]

1.0

In [10]:
print(np1.shape)

(4,)


In [11]:
matrix = [
    [1,2,5,8],
    [1,2,5,8],
    [1,2,5,8]
]
np.array(matrix, int).shape

(3, 4)

In [24]:
rank3 = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    # 추가하면 어떤 값이 증가하는가?
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], 
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], 
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
]
np.array(rank3, int).shape


(6, 3, 4)

In [25]:
# 차원수
np.array(tensor_rank3, int).ndim

3

In [26]:
# 전체 갯수 4 * 3 * 4
np.array(tensor_rank3, int).size

48

In [27]:
# 전체 갯수 4 * 3 * 4
np.array(tensor_rank3, int).size

48

In [28]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=int)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
np.array( [ [1, 2, 3.5], [4, 5, 6.5]], dtype=float)

array([[1. , 2. , 3.5],
       [4. , 5. , 6.5]])